services:
  - type: web
    name: whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_PREFIX
        value: "!"
      - key: DASHBOARD_PORT
        value: "10000"
    autoDeploy: true
